from turtle import*
speed(10)
def matahari():
    color('yellow')
    begin_fill()
    circle(32)
    end_fill()
def awan():
    penup()
    goto(110, 232)
    pendown()
    color('#86b0c0')
    begin_fill()
    circle(32)
    end_fill()
    penup()
    goto(100, 200)
    pendown()
    color('#86b0c0')
    begin_fill()
    circle(32)
    end_fill()
    penup()
    goto(132, 200)
    pendown()
    color('#86b0c0')
    begin_fill()
    circle(32)
    end_fill()
    penup()
    begin_fill()
    circle(32)
    end_fill()
def rumput():
    begin_fill()
    penup()
    goto( -1000, 0)
    pendown()
    color('green')
    forward(1900)
    right(90)
    forward(10)
    right(90)
    forward(1900)
    right(90)
    forward(10)
    end_fill()
def segitiga():
    begin_fill()
    color('rgb(78, 3, 3)')
    for i in range(3):
        left(120)
        forward(100)
    end_fill()
def rumah():
    color("#eaeaeaea")
    begin_fill()
    for i in range(4):
        forward(100)
        right(90)
    end_fill()
    forward(100)
    segitiga()
def kaca():
    for i in range(4):
        begin_fill()
        color("skyblue")
        forward(10)
        right(90)
        forward(10)
        right(90)
        forward(10)
        right(90)
        forward(10)
        right(90)
        end_fill()
def gagang_pintu():
    color('yellow')
    begin_fill()
    circle(3)
    end_fill()
def pintu():
    color("brown")
    begin_fill()
    for i in range(2):
        forward(32)
        right(90)
        forward(50)
        right(90)
    end_fill()
rumput()
penup()
goto(0, 100)
pendown()
right(90)
rumah()
penup()
goto(10, 50)
pendown()
kaca()
penup()
goto(30, 50)
pendown()
kaca()
penup()
goto(50, 50)
pendown()
kaca()
penup()
goto(70, 50)
pendown()
pintu()
penup()
goto(95, 16)
pendown()
gagang_pintu()
awan()
penup()
goto(160, 232)
pendown()
matahari()
hideturtle()
exitonclick()
